# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SmartLabeller(object):
    def setupUi(self, SmartLabeller):
        SmartLabeller.setObjectName("SmartLabeller")
        SmartLabeller.resize(1000, 1000)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SmartLabeller.sizePolicy().hasHeightForWidth())
        SmartLabeller.setSizePolicy(sizePolicy)
        SmartLabeller.setMinimumSize(QtCore.QSize(500, 500))
        SmartLabeller.setMouseTracking(True)
        SmartLabeller.setToolTip("")
        SmartLabeller.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(SmartLabeller)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.verticalTabWidget.setGeometry(QtCore.QRect(-10, 0, 1000, 1000))
        self.verticalTabWidget.setMouseTracking(True)
        self.verticalTabWidget.setUsesScrollButtons(True)
        self.verticalTabWidget.setObjectName("verticalTabWidget")
        self.verticalTabWidgetPage1 = QtWidgets.QWidget()
        self.verticalTabWidgetPage1.setObjectName("verticalTabWidgetPage1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalTabWidgetPage1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalTabWidget.addTab(self.verticalTabWidgetPage1, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 1000, 1000))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 984, 984))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setGeometry(QtCore.QRect(30, 20, 141, 25))
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox.setGeometry(QtCore.QRect(30, 90, 150, 25))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox_2.setGeometry(QtCore.QRect(30, 160, 150, 25))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox_3.setGeometry(QtCore.QRect(30, 220, 150, 25))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox_4.setGeometry(QtCore.QRect(30, 290, 150, 25))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.pushButton_5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_5.setGeometry(QtCore.QRect(300, 360, 89, 25))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_4.setGeometry(QtCore.QRect(210, 350, 35, 35))
        self.pushButton_4.setStyleSheet("background-color: rgb(0, 255, 95);\n"
"font: 20pt \"Ubuntu\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.comboBox_5 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox_5.setGeometry(QtCore.QRect(30, 360, 150, 25))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setGeometry(QtCore.QRect(30, 340, 141, 21))
        self.label_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_9.setObjectName("label_9")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setGeometry(QtCore.QRect(30, 270, 141, 21))
        self.label_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setGeometry(QtCore.QRect(30, 200, 141, 21))
        self.label_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setGeometry(QtCore.QRect(30, 140, 67, 21))
        self.label_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setGeometry(QtCore.QRect(30, 70, 67, 21))
        self.label_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_5.setObjectName("label_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_2.setGeometry(QtCore.QRect(380, 230, 31, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(430, 30, 450, 450))
        self.label.setStyleSheet("")
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_3.setGeometry(QtCore.QRect(900, 230, 31, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(520, 520, 350, 20))
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setText("")
        self.label_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setGeometry(QtCore.QRect(520, 490, 350, 20))
        self.label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_4.setText("")
        self.label_4.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(540, 10, 350, 20))
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setGeometry(QtCore.QRect(450, 780, 350, 20))
        self.label_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.tableWidget = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.tableWidget.setGeometry(QtCore.QRect(30, 400, 256, 192))
        self.tableWidget.setRowCount(10)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.pushButton_6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_6.setGeometry(QtCore.QRect(300, 280, 89, 25))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_7.setGeometry(QtCore.QRect(300, 320, 89, 25))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setGeometry(QtCore.QRect(210, 70, 67, 21))
        self.label_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_11.setObjectName("label_11")
        self.lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit.setGeometry(QtCore.QRect(210, 90, 150, 25))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setGeometry(QtCore.QRect(300, 530, 111, 21))
        self.label_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_12.setObjectName("label_12")
        self.pushButton_8 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_8.setGeometry(QtCore.QRect(650, 590, 141, 25))
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setGeometry(QtCore.QRect(520, 570, 111, 21))
        self.label_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_13.setObjectName("label_13")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_2.setGeometry(QtCore.QRect(520, 590, 113, 25))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.plainTextEdit.setGeometry(QtCore.QRect(300, 550, 161, 70))
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton_9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_9.setGeometry(QtCore.QRect(300, 140, 89, 25))
        self.pushButton_9.setObjectName("pushButton_9")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalTabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea_2.setGeometry(QtCore.QRect(0, 0, 1000, 1000))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 998, 998))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.tableView = QtWidgets.QTableView(self.scrollAreaWidgetContents_2)
        self.tableView.setGeometry(QtCore.QRect(20, 30, 320, 400))
        self.tableView.setStyleSheet("")
        self.tableView.setObjectName("tableView")
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_14.setGeometry(QtCore.QRect(490, 40, 121, 17))
        self.label_14.setObjectName("label_14")
        self.spinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.spinBox.setGeometry(QtCore.QRect(610, 30, 48, 26))
        self.spinBox.setMinimum(55)
        self.spinBox.setObjectName("spinBox")
        self.tableView_2 = QtWidgets.QTableView(self.scrollAreaWidgetContents_2)
        self.tableView_2.setGeometry(QtCore.QRect(490, 70, 400, 400))
        self.tableView_2.setStyleSheet("")
        self.tableView_2.setObjectName("tableView_2")
        self.pushButton_10 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_10.setGeometry(QtCore.QRect(680, 30, 89, 25))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_11.setGeometry(QtCore.QRect(790, 30, 89, 25))
        self.pushButton_11.setObjectName("pushButton_11")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalTabWidget.addTab(self.tab_2, "")
        SmartLabeller.setCentralWidget(self.centralwidget)
        self.actionFile = QtWidgets.QAction(SmartLabeller)
        self.actionFile.setObjectName("actionFile")
        self.actionHelp = QtWidgets.QAction(SmartLabeller)
        self.actionHelp.setObjectName("actionHelp")

        self.retranslateUi(SmartLabeller)
        self.verticalTabWidget.setCurrentIndex(1)
        self.pushButton_5.clicked.connect(SmartLabeller.save_item)
        self.pushButton_8.clicked.connect(SmartLabeller.combine_json)
        self.pushButton_6.clicked.connect(SmartLabeller.clear_all)
        self.pushButton_3.clicked.connect(SmartLabeller.right_scroll)
        self.pushButton_7.clicked.connect(SmartLabeller.clear_last)
        self.pushButton.clicked.connect(SmartLabeller.mybutton_clicked)
        self.pushButton_2.clicked.connect(SmartLabeller.left_scroll)
        self.pushButton_4.clicked.connect(SmartLabeller.append_item)
        self.pushButton_9.clicked.connect(SmartLabeller.delete_image)
        self.pushButton_10.clicked.connect(SmartLabeller.data_split)
        self.pushButton_11.clicked.connect(SmartLabeller.save_split)
        QtCore.QMetaObject.connectSlotsByName(SmartLabeller)

    def retranslateUi(self, SmartLabeller):
        _translate = QtCore.QCoreApplication.translate
        SmartLabeller.setWindowTitle(_translate("SmartLabeller", "Smart Labeller"))
        self.verticalTabWidget.setTabText(self.verticalTabWidget.indexOf(self.verticalTabWidgetPage1), _translate("SmartLabeller", ":"))
        self.pushButton.setText(_translate("SmartLabeller", "Browse folder"))
        self.comboBox.setItemText(0, _translate("SmartLabeller", "Select"))
        self.comboBox.setItemText(1, _translate("SmartLabeller", "Elevation"))
        self.comboBox.setItemText(2, _translate("SmartLabeller", "Interior"))
        self.comboBox_2.setItemText(0, _translate("SmartLabeller", "Select"))
        self.comboBox_2.setItemText(1, _translate("SmartLabeller", "Ceiling"))
        self.comboBox_2.setItemText(2, _translate("SmartLabeller", "Gutter"))
        self.comboBox_2.setItemText(3, _translate("SmartLabeller", "Roof"))
        self.comboBox_2.setItemText(4, _translate("SmartLabeller", "Stucco"))
        self.comboBox_2.setItemText(5, _translate("SmartLabeller", "Vent"))
        self.comboBox_2.setItemText(6, _translate("SmartLabeller", "Downspout"))
        self.comboBox_2.setItemText(7, _translate("SmartLabeller", "Door"))
        self.comboBox_2.setItemText(8, _translate("SmartLabeller", "Windows"))
        self.comboBox_3.setItemText(0, _translate("SmartLabeller", "Select"))
        self.comboBox_3.setItemText(1, _translate("SmartLabeller", "No Damage"))
        self.comboBox_3.setItemText(2, _translate("SmartLabeller", "Non Peril Damage"))
        self.comboBox_3.setItemText(3, _translate("SmartLabeller", "Peril Damage"))
        self.comboBox_4.setItemText(0, _translate("SmartLabeller", "Select"))
        self.comboBox_4.setItemText(1, _translate("SmartLabeller", "Plastic"))
        self.comboBox_4.setItemText(2, _translate("SmartLabeller", "Rubber"))
        self.comboBox_4.setItemText(3, _translate("SmartLabeller", "Steel"))
        self.comboBox_4.setItemText(4, _translate("SmartLabeller", "Aluminium"))
        self.comboBox_4.setItemText(5, _translate("SmartLabeller", "Paint"))
        self.comboBox_4.setItemText(6, _translate("SmartLabeller", "Glass"))
        self.comboBox_4.setItemText(7, _translate("SmartLabeller", "Wood"))
        self.pushButton_5.setText(_translate("SmartLabeller", "Save"))
        self.pushButton_4.setText(_translate("SmartLabeller", "+"))
        self.comboBox_5.setItemText(0, _translate("SmartLabeller", "Select"))
        self.comboBox_5.setItemText(1, _translate("SmartLabeller", "½ \""))
        self.comboBox_5.setItemText(2, _translate("SmartLabeller", "1-3 \""))
        self.comboBox_5.setItemText(3, _translate("SmartLabeller", "4 \""))
        self.comboBox_5.setItemText(4, _translate("SmartLabeller", "5-7 \""))
        self.comboBox_5.setItemText(5, _translate("SmartLabeller", "8+ \""))
        self.label_9.setText(_translate("SmartLabeller", "<html><head/><body><p><span style=\" font-weight:600; color:#4000ff;\">Material Size</span></p></body></html>"))
        self.label_8.setText(_translate("SmartLabeller", "<html><head/><body><p><span style=\" font-weight:600; color:#4000ff;\">Material Type</span></p></body></html>"))
        self.label_7.setText(_translate("SmartLabeller", "<html><head/><body><p><span style=\" font-weight:600; color:#4000ff;\">Damage Type</span></p></body></html>"))
        self.label_6.setText(_translate("SmartLabeller", "<html><head/><body><p><span style=\" font-weight:600; color:#4000ff;\">Item</span></p></body></html>"))
        self.label_5.setText(_translate("SmartLabeller", "<html><head/><body><p><span style=\" font-weight:600; color:#4000ff;\">View</span></p></body></html>"))
        self.pushButton_2.setText(_translate("SmartLabeller", "<"))
        self.pushButton_3.setText(_translate("SmartLabeller", ">"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_6.setText(_translate("SmartLabeller", "Clear all"))
        self.pushButton_7.setText(_translate("SmartLabeller", "Clear last"))
        self.label_11.setText(_translate("SmartLabeller", "<html><head/><body><p><span style=\" font-weight:600; color:#4000ff;\">Json File</span></p></body></html>"))
        self.label_12.setText(_translate("SmartLabeller", "<html><head/><body><p><span style=\" font-weight:600; color:#4000ff;\">Json List</span></p></body></html>"))
        self.pushButton_8.setText(_translate("SmartLabeller", "Combine Json"))
        self.label_13.setText(_translate("SmartLabeller", "<html><head/><body><p><span style=\" font-weight:600; color:#4000ff;\">New File Name</span></p></body></html>"))
        self.pushButton_9.setText(_translate("SmartLabeller", "Delete img"))
        self.verticalTabWidget.setTabText(self.verticalTabWidget.indexOf(self.tab), _translate("SmartLabeller", "Home"))
        self.label_14.setText(_translate("SmartLabeller", "Train Test Split:"))
        self.pushButton_10.setText(_translate("SmartLabeller", "Split"))
        self.pushButton_11.setText(_translate("SmartLabeller", "Save split"))
        self.verticalTabWidget.setTabText(self.verticalTabWidget.indexOf(self.tab_2), _translate("SmartLabeller", "Data"))
        self.actionFile.setText(_translate("SmartLabeller", "File"))
        self.actionHelp.setText(_translate("SmartLabeller", "Help"))


import test_rc
